#!/usr/bin/env bash
# REPRODUCE.sh — AEA-compliant replication-package recipe.
#
# Researcher Toolkit plan Task 8 (D-05). Generated by `redist analyze --paper-mode`
# (when shipped). This template ships at scripts/research/paper_mode_template/REPRODUCE.sh
# and is rendered with substituted values into each paper-mode replication package.
#
# AEA Data and Code Availability Policy compliance:
# - Target platform pinned (Linux x86_64 glibc 2.35) — D-05 explicit
# - Cargo.lock SHA recorded + verified
# - rust-toolchain.toml SHA recorded + verified
# - requirements.lock SHA recorded + verified
# - Expected output checksums per step
# - Wall-clock budget: <= 30 minutes on a 4-core laptop (D-05 contract)
#
# Cross-platform reviewers (macOS, Windows): use WSL or a Linux VM with the
# pinned glibc version. The script exits with an actionable note on mismatch
# rather than producing a misleading checksum diff.
#
# Variables substituted at render time (placeholders below):
#   {{REDIST_VERSION}}       — semver of the binary at paper-mode time
#   {{REDIST_BUILD_COMMIT}}  — full git SHA
#   {{CARGO_LOCK_SHA256}}    — SHA-256 of Cargo.lock
#   {{RUST_TOOLCHAIN_SHA256}} — SHA-256 of rust-toolchain.toml
#   {{REQUIREMENTS_LOCK_SHA256}} — SHA-256 of requirements.lock
#   {{TARGET_PLATFORM}}      — "linux-x86_64-glibc-2.35"
#   {{ANALYZE_INVOCATION}}   — the exact `redist analyze ...` command to rerun
#   {{EXPECTED_OUTPUTS_JSON}} — path to expected_outputs.sha256.json

set -euo pipefail

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
TARGET_PLATFORM="{{TARGET_PLATFORM}}"

step() { echo; echo "=== $1 ==="; }
ok()   { echo "[OK] $*"; }
fail() { echo "[FAIL] $*" >&2; exit 1; }

# ── Step 1: platform check ───────────────────────────────────────────────────
step "Step 1 — platform verification"
ARCH="$(uname -m)"
KERNEL="$(uname -s)"
if ! command -v ldd >/dev/null 2>&1; then
    fail "ldd not found; this script targets Linux. On macOS/Windows, run inside WSL or a Linux VM matching $TARGET_PLATFORM."
fi
GLIBC_VERSION="$(ldd --version 2>&1 | head -1 | grep -oE '[0-9]+\.[0-9]+' | head -1 || echo unknown)"

case "$TARGET_PLATFORM" in
    "linux-x86_64-glibc-2.35")
        if [ "$ARCH" != "x86_64" ] || [ "$KERNEL" != "Linux" ] || [ "$GLIBC_VERSION" != "2.35" ]; then
            echo "[WARN] platform mismatch:"
            echo "       Expected: $TARGET_PLATFORM"
            echo "       Got:      ${KERNEL}-${ARCH}-glibc-${GLIBC_VERSION}"
            echo
            echo "       AEA replication: outputs may not match published checksums byte-for-byte"
            echo "       on a non-target platform. The methodology should still produce"
            echo "       statistically equivalent results (up to floating-point rounding)."
            echo
            echo "       To exactly reproduce: use WSL2 with Ubuntu 22.04 (glibc 2.35) or a"
            echo "       Docker container based on ubuntu:22.04. See README.md in the"
            echo "       replication package for the exact Docker recipe."
            echo
            read -r -p "       Continue anyway? [y/N] " continue_anyway
            [ "$continue_anyway" = "y" ] || fail "aborted by user"
        else
            ok "platform matches target ($TARGET_PLATFORM)"
        fi
        ;;
    *)
        echo "[WARN] unrecognized TARGET_PLATFORM '$TARGET_PLATFORM'; proceeding without check"
        ;;
esac

# ── Step 2: clone + checkout the recorded build commit ───────────────────────
step "Step 2 — repository state"
if [ ! -d "$REPO_ROOT/.git" ]; then
    fail "$REPO_ROOT is not a git repository. Clone the project + run REPRODUCE.sh from the package directory."
fi

cd "$REPO_ROOT"
EXPECTED_COMMIT="{{REDIST_BUILD_COMMIT}}"
ACTUAL_COMMIT="$(git rev-parse HEAD)"
if [ "$ACTUAL_COMMIT" != "$EXPECTED_COMMIT" ]; then
    echo "[INFO] checking out recorded build commit: $EXPECTED_COMMIT"
    git checkout "$EXPECTED_COMMIT" || fail "git checkout failed; the commit may not exist locally — try `git fetch --all` first"
fi
ok "at commit $EXPECTED_COMMIT"

# ── Step 3: verify lockfile SHAs ─────────────────────────────────────────────
step "Step 3 — lockfile verification"
sha_of() { sha256sum "$1" 2>/dev/null | awk '{print $1}' || shasum -a 256 "$1" | awk '{print $1}'; }

EXPECTED_CARGO_LOCK_SHA="{{CARGO_LOCK_SHA256}}"
EXPECTED_TOOLCHAIN_SHA="{{RUST_TOOLCHAIN_SHA256}}"
EXPECTED_REQS_SHA="{{REQUIREMENTS_LOCK_SHA256}}"

[ -f "$REPO_ROOT/redist/Cargo.lock" ] || fail "missing redist/Cargo.lock"
ACTUAL_CARGO_LOCK_SHA=$(sha_of "$REPO_ROOT/redist/Cargo.lock")
[ "$ACTUAL_CARGO_LOCK_SHA" = "$EXPECTED_CARGO_LOCK_SHA" ] \
    || fail "Cargo.lock SHA mismatch: expected $EXPECTED_CARGO_LOCK_SHA, got $ACTUAL_CARGO_LOCK_SHA"
ok "Cargo.lock matches"

if [ -f "$REPO_ROOT/redist/rust-toolchain.toml" ]; then
    ACTUAL_TOOLCHAIN_SHA=$(sha_of "$REPO_ROOT/redist/rust-toolchain.toml")
    [ "$ACTUAL_TOOLCHAIN_SHA" = "$EXPECTED_TOOLCHAIN_SHA" ] \
        || fail "rust-toolchain.toml SHA mismatch: expected $EXPECTED_TOOLCHAIN_SHA, got $ACTUAL_TOOLCHAIN_SHA"
    ok "rust-toolchain.toml matches"
fi

if [ -f "$REPO_ROOT/requirements.lock" ]; then
    ACTUAL_REQS_SHA=$(sha_of "$REPO_ROOT/requirements.lock")
    [ "$ACTUAL_REQS_SHA" = "$EXPECTED_REQS_SHA" ] \
        || fail "requirements.lock SHA mismatch: expected $EXPECTED_REQS_SHA, got $ACTUAL_REQS_SHA"
    ok "requirements.lock matches"
fi

# ── Step 4: build redist with --locked ───────────────────────────────────────
step "Step 4 — build redist (locked dependencies)"
cd "$REPO_ROOT/redist"
cargo build --release --locked --bin redist || fail "cargo build failed; see above"
ok "redist built ($(./target/release/redist --version 2>&1 | head -1))"

# ── Step 5: install pinned Python dependencies ───────────────────────────────
step "Step 5 — install pinned Python dependencies"
cd "$REPO_ROOT"
if [ -f "requirements.lock" ]; then
    if ! command -v pip >/dev/null 2>&1; then
        fail "pip not found; install Python 3.11 first"
    fi
    pip install --quiet -r requirements.lock || fail "pip install failed"
    ok "requirements.lock installed"
else
    echo "[SKIP] no requirements.lock; this paper-mode package has no Python dependencies"
fi

# ── Step 6: re-run the analyze invocation ────────────────────────────────────
step "Step 6 — re-run analyze invocation"
cd "$REPO_ROOT"
ANALYZE_CMD='{{ANALYZE_INVOCATION}}'
echo "$ ANALYZE_CMD"
eval "$ANALYZE_CMD" || fail "analyze re-run failed"

# ── Step 7: verify output checksums ──────────────────────────────────────────
step "Step 7 — verify output checksums"
EXPECTED_OUTPUTS_JSON="{{EXPECTED_OUTPUTS_JSON}}"
[ -f "$EXPECTED_OUTPUTS_JSON" ] || fail "expected outputs JSON missing: $EXPECTED_OUTPUTS_JSON"

# Walk the expected_outputs JSON. Each entry: {path, sha256}.
# Use jq if available; fall back to a Python one-liner.
if command -v jq >/dev/null 2>&1; then
    diff_count=0
    while IFS= read -r row; do
        path=$(echo "$row" | jq -r '.path')
        expected=$(echo "$row" | jq -r '.sha256')
        if [ ! -f "$path" ]; then
            echo "[FAIL] missing output: $path"
            diff_count=$((diff_count + 1))
            continue
        fi
        actual=$(sha_of "$path")
        if [ "$actual" != "$expected" ]; then
            echo "[FAIL] SHA mismatch: $path"
            echo "       expected: $expected"
            echo "       got:      $actual"
            diff_count=$((diff_count + 1))
        else
            ok "$path"
        fi
    done < <(jq -c '.outputs[]' "$EXPECTED_OUTPUTS_JSON")
    [ "$diff_count" -eq 0 ] || fail "$diff_count output(s) failed checksum verification"
else
    echo "[SKIP] jq not installed; cannot verify output checksums automatically"
    echo "       Install jq, OR open $EXPECTED_OUTPUTS_JSON and verify manually"
    echo "       with sha256sum on each listed path."
fi

# ── Done ─────────────────────────────────────────────────────────────────────
echo
echo "=========================================="
echo "[OK] AEA replication SUCCESS"
echo "  redist version: {{REDIST_VERSION}}"
echo "  build commit:   {{REDIST_BUILD_COMMIT}}"
echo "  target platform: $TARGET_PLATFORM"
echo
echo "Cite this run in a paper as:"
echo "  redist v{{REDIST_VERSION}} (commit {{REDIST_BUILD_COMMIT}})"
echo "  see docs/file-formats/citation-strings.md for full citation templates"
echo "=========================================="
