#!/usr/bin/env python3
"""
Generate a self-contained dashboard HTML with all state maps embedded as base64.
Reads outputs/V1/2020/index.html, embeds map PNGs, writes docs/dashboard.html.
"""

import base64
import io
import re
import sys
from pathlib import Path

from PIL import Image

OUTPUTS_DIR = Path('outputs/V1/2020')
DASHBOARD_SRC = OUTPUTS_DIR / 'index.html'
DASHBOARD_OUT = Path('docs/dashboard.html')

# Resize all_districts maps to this width (px). Round maps to 60% of this.
MAP_WIDTH = 600
ROUND_WIDTH = 450
JPEG_QUALITY = 72


def encode_image(img_path: Path, max_width: int) -> str | None:
    if not img_path.exists():
        return None
    try:
        img = Image.open(img_path).convert('RGB')  # JPEG needs RGB
        w, h = img.size
        if w > max_width:
            new_h = int(h * max_width / w)
            img = img.resize((max_width, new_h), Image.LANCZOS)
        buf = io.BytesIO()
        img.save(buf, format='JPEG', quality=JPEG_QUALITY, optimize=True)
        data = base64.b64encode(buf.getvalue()).decode('ascii')
        return f'data:image/jpeg;base64,{data}'
    except Exception as e:
        print(f'  [WARN] Could not encode {img_path}: {e}', file=sys.stderr)
        return None


def build_map_table() -> dict[str, str]:
    """Build mapping of relative path (no extension) -> data URI."""
    table: dict[str, str] = {}
    states_dir = OUTPUTS_DIR / 'states'
    if not states_dir.exists():
        print(f'[ERROR] {states_dir} not found', file=sys.stderr)
        return table

    state_dirs = sorted(p for p in states_dir.iterdir() if p.is_dir())
    print(f'Embedding maps for {len(state_dirs)} states...')

    for state_dir in state_dirs:
        state = state_dir.name
        maps_dir = state_dir / 'maps'

        # all_districts
        src = encode_image(maps_dir / 'all_districts.png', MAP_WIDTH)
        if src:
            table[f'{state}/maps/all_districts'] = src
            print(f'  {state}: all_districts ({len(src)//1024}KB)')

        # all_districts_with_cities
        src = encode_image(maps_dir / 'all_districts_with_cities.png', MAP_WIDTH)
        if src:
            table[f'{state}/maps/all_districts_with_cities'] = src

        # round maps
        rounds_dir = maps_dir / 'rounds'
        if rounds_dir.exists():
            for rnd in sorted(rounds_dir.glob('round_*.png')):
                key = f'{state}/maps/rounds/{rnd.stem}'
                src = encode_image(rnd, ROUND_WIDTH)
                if src:
                    table[key] = src

    return table


def patch_html(html: str, table: dict[str, str]) -> str:
    # 1. Build the JS lookup object and helper function, inject before </body>
    entries = ',\n'.join(
        f'    {repr(k)}: {repr(v[:40])}...' for k, v in list(table.items())[:3]
    )
    # Actual full data
    js_entries = ',\n'.join(f'    {repr(k)}: {repr(v)}' for k, v in table.items())
    injection = f"""
<script>
// Embedded map images (base64) — generated by embed_maps_dashboard.py
const EMBEDDED_MAPS = {{
{js_entries}
}};

function getEmbeddedMap(state, relPath) {{
    // relPath is like "maps/all_districts" or "maps/rounds/round_01"
    const key = state + '/' + relPath;
    return EMBEDDED_MAPS[key] || null;
}}
</script>
"""

    # 2. Patch img src template literals to use embedded data when available.
    #    Pattern: src="${basePath}/states/${state}/maps/..."
    #    We wrap each with an onerror fallback and also set src via JS on load.
    #
    #    Strategy: replace the template literal src with a call to a helper
    #    that returns the embedded data URI or falls back to the original path.
    #
    #    In template literals inside JS, patterns look like:
    #    `<img src="${basePath}/states/${state}/maps/all_districts.png" ...>`
    #
    #    We transform:
    #    src="${basePath}/states/${state}/maps/RELPATH.png"
    #    -> src="${getEmbeddedMap(state, 'maps/RELPATH') || basePath+'/states/'+state+'/maps/RELPATH.png'}"

    def replace_map_src(m: re.Match) -> str:
        rel = m.group(1)  # e.g. "maps/all_districts" or "maps/rounds/round_${roundNumPadded}"
        # Keep dynamic round references as-is in the fallback
        fallback = "${basePath}/states/${state}/" + rel + ".png"
        embedded = "${getEmbeddedMap(state, '" + rel + "') || '" + fallback + "'}"
        return f'src="{embedded}"'

    # Match src="${basePath}/states/${state}/RELPATH.png"
    html = re.sub(
        r'src="\$\{basePath\}/states/\$\{state\}/([^"]+?)\.png"',
        replace_map_src,
        html
    )

    # Also handle the concatenation style: basePath + '/states/' + state + '/maps/...'
    def replace_concat_src(m: re.Match) -> str:
        rel = m.group(1)
        return f"getEmbeddedMap(state, '{rel}') || (basePath + '/states/' + state + '/{rel}.png')"

    html = re.sub(
        r"basePath \+ '/states/' \+ state \+ '/([^']+?)\.png'",
        replace_concat_src,
        html
    )

    # 3. Inject the script block before </body>
    html = html.replace('</body>', injection + '</body>')

    return html


def main():
    if not DASHBOARD_SRC.exists():
        print(f'[ERROR] Source dashboard not found: {DASHBOARD_SRC}', file=sys.stderr)
        sys.exit(1)

    print(f'Reading {DASHBOARD_SRC}...')
    html = DASHBOARD_SRC.read_text(encoding='utf-8')

    table = build_map_table()
    total_kb = sum(len(v) for v in table.values()) // 1024
    print(f'Built table: {len(table)} images, ~{total_kb}KB base64 total')

    print('Patching HTML...')
    html = patch_html(html, table)

    DASHBOARD_OUT.parent.mkdir(parents=True, exist_ok=True)
    DASHBOARD_OUT.write_text(html, encoding='utf-8')
    size_kb = DASHBOARD_OUT.stat().st_size // 1024
    print(f'[OK] Written to {DASHBOARD_OUT} ({size_kb}KB)')


if __name__ == '__main__':
    main()
