"""
State configuration data for all census years.

District counts for each state by census year.
"""

# State FIPS codes (same across all years)
STATE_FIPS = {
    "01": "alabama",
    "02": "alaska",
    "04": "arizona",
    "05": "arkansas",
    "06": "california",
    "08": "colorado",
    "09": "connecticut",
    "10": "delaware",
    # "11": "district_of_columbia",  # DC has no congressional districts
    "12": "florida",
    "13": "georgia",
    "15": "hawaii",
    "16": "idaho",
    "17": "illinois",
    "18": "indiana",
    "19": "iowa",
    "20": "kansas",
    "21": "kentucky",
    "22": "louisiana",
    "23": "maine",
    "24": "maryland",
    "25": "massachusetts",
    "26": "michigan",
    "27": "minnesota",
    "28": "mississippi",
    "29": "missouri",
    "30": "montana",
    "31": "nebraska",
    "32": "nevada",
    "33": "new_hampshire",
    "34": "new_jersey",
    "35": "new_mexico",
    "36": "new_york",
    "37": "north_carolina",
    "38": "north_dakota",
    "39": "ohio",
    "40": "oklahoma",
    "41": "oregon",
    "42": "pennsylvania",
    "44": "rhode_island",
    "45": "south_carolina",
    "46": "south_dakota",
    "47": "tennessee",
    "48": "texas",
    "49": "utah",
    "50": "vermont",
    "51": "virginia",
    "53": "washington",
    "54": "west_virginia",
    "55": "wisconsin",
    "56": "wyoming",
}

# 2020 Census district counts
STATE_DISTRICTS_2020 = {
    "alabama": 7,
    "alaska": 1,
    "arizona": 9,
    "arkansas": 4,
    "california": 52,
    "colorado": 8,
    "connecticut": 5,
    "delaware": 1,
    # "district_of_columbia": 1,  # DC has no congressional districts
    "florida": 28,
    "georgia": 14,
    "hawaii": 2,
    "idaho": 2,
    "illinois": 17,
    "indiana": 9,
    "iowa": 4,
    "kansas": 4,
    "kentucky": 6,
    "louisiana": 6,
    "maine": 2,
    "maryland": 8,
    "massachusetts": 9,
    "michigan": 13,
    "minnesota": 8,
    "mississippi": 4,
    "missouri": 8,
    "montana": 2,
    "nebraska": 3,
    "nevada": 4,
    "new_hampshire": 2,
    "new_jersey": 12,
    "new_mexico": 3,
    "new_york": 26,
    "north_carolina": 14,
    "north_dakota": 1,
    "ohio": 15,
    "oklahoma": 5,
    "oregon": 6,
    "pennsylvania": 17,
    "rhode_island": 2,
    "south_carolina": 7,
    "south_dakota": 1,
    "tennessee": 9,
    "texas": 38,
    "utah": 4,
    "vermont": 1,
    "virginia": 11,
    "washington": 10,
    "west_virginia": 2,
    "wisconsin": 8,
    "wyoming": 1,
}

# 2010 Census district counts
STATE_DISTRICTS_2010 = {
    "alabama": 7,
    "alaska": 1,
    "arizona": 9,
    "arkansas": 4,
    "california": 53,
    "colorado": 7,
    "connecticut": 5,
    "delaware": 1,
    # "district_of_columbia": 1,  # DC has no congressional districts
    "florida": 27,
    "georgia": 14,
    "hawaii": 2,
    "idaho": 2,
    "illinois": 18,
    "indiana": 9,
    "iowa": 4,
    "kansas": 4,
    "kentucky": 6,
    "louisiana": 6,
    "maine": 2,
    "maryland": 8,
    "massachusetts": 9,
    "michigan": 14,
    "minnesota": 8,
    "mississippi": 4,
    "missouri": 8,
    "montana": 1,
    "nebraska": 3,
    "nevada": 4,
    "new_hampshire": 2,
    "new_jersey": 12,
    "new_mexico": 3,
    "new_york": 27,
    "north_carolina": 13,
    "north_dakota": 1,
    "ohio": 16,
    "oklahoma": 5,
    "oregon": 5,
    "pennsylvania": 18,
    "rhode_island": 2,
    "south_carolina": 7,
    "south_dakota": 1,
    "tennessee": 9,
    "texas": 36,
    "utah": 4,
    "vermont": 1,
    "virginia": 11,
    "washington": 10,
    "west_virginia": 3,
    "wisconsin": 8,
    "wyoming": 1,
}

# 2000 Census district counts
STATE_DISTRICTS_2000 = {
    "alabama": 7,
    "alaska": 1,
    "arizona": 8,
    "arkansas": 4,
    "california": 53,
    "colorado": 7,
    "connecticut": 5,
    "delaware": 1,
    # "district_of_columbia": 1,  # DC has no congressional districts
    "florida": 25,
    "georgia": 13,
    "hawaii": 2,
    "idaho": 2,
    "illinois": 19,
    "indiana": 9,
    "iowa": 5,
    "kansas": 4,
    "kentucky": 6,
    "louisiana": 7,
    "maine": 2,
    "maryland": 8,
    "massachusetts": 10,
    "michigan": 15,
    "minnesota": 8,
    "mississippi": 4,
    "missouri": 9,
    "montana": 1,
    "nebraska": 3,
    "nevada": 3,
    "new_hampshire": 2,
    "new_jersey": 13,
    "new_mexico": 3,
    "new_york": 29,
    "north_carolina": 13,
    "north_dakota": 1,
    "ohio": 18,
    "oklahoma": 5,
    "oregon": 5,
    "pennsylvania": 19,
    "rhode_island": 2,
    "south_carolina": 6,
    "south_dakota": 1,
    "tennessee": 9,
    "texas": 32,
    "utah": 3,
    "vermont": 1,
    "virginia": 11,
    "washington": 9,
    "west_virginia": 3,
    "wisconsin": 8,
    "wyoming": 1,
}


def get_state_districts(year: str) -> dict:
    """Get state districts for a given year."""
    if year == "2020":
        return STATE_DISTRICTS_2020
    elif year == "2010":
        return STATE_DISTRICTS_2010
    elif year == "2000":
        return STATE_DISTRICTS_2000
    else:
        raise ValueError(f"Invalid year: {year}")
